-- Create table
create table T400PARAM
(
  PARAMETRO VARCHAR(20),
  VALOR     NUMERIC(15,2),
  DESCONTO  NUMERIC(15,2),
  PARCELA   NUMERIC(3),
  CLIENTE   NUMERIC(5),
  CONTRATO  NUMERIC(5),
  LOTE      NUMERIC(5)
)